### ISSUE TITLE
Create the API client wrapping the gRPC calls

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-client-dispatch-python#12]
### What's needed?

We need to provide a channels-streamed version of the gRPC functions.

### Proposed solution

Use the base client helper function:

* https://github.com/frequenz-floss/frequenz-client-base-python/

See, for example, the weather API client:

* https://github.com/frequenz-floss/frequenz-api-weather/blob/v0.x.x/py/frequenz/client/weather/_client.py

**Comment by Marenz** [comment]
There is no streaming interface in the dispatch protobuf though? Only polling based functions.

**Comment by Marenz** [comment]
Probably depends on https://github.com/frequenz-floss/frequenz-api-dispatch/issues/84

**Comment by llucax** [comment]
Yeah, the API is a bit weird. The polling interface should be enough to build the higher level abstractions though.

I think there was a reason for this, but @stefan-brus-frequenz is probably the person to ask as I don´t remember anything specific.

**Comment by Marenz** [comment]
>  as I don´t remember anything ~specific~.

:angel:

**Comment by Marenz** [comment]
This is basically done through https://github.com/frequenz-floss/frequenz-dispatch-python/pulls now
