### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-client-dispatch-python#13]
### What happened?

The CI is failing, ~probably because of~:

* ~https://github.com/frequenz-floss/frequenz-client-dispatch-python/pull/6~

### What did you expect instead?

To pass.

### Affected part(s)

Build script, CI, dependencies, etc. (part:tooling)

### Extra information

* ~https://github.com/frequenz-floss/frequenz-client-dispatch-python/pull/6#issuecomment-1923483855~

**Comment by Marenz** [comment]
No, the CI is failing because we have no working code or tests..
