### ISSUE TITLE
Add a `calculate_next_run()` method to `Dispatch`

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-client-dispatch-python#28]
The `frequenz-dispatch` project provides a function to calculate the next run time for a dispatch, which is probably useful to have in the client, as any user of the API client will probably want to do this.

The method should also expose the `from` argument (without the `_`), as users might want to calculate the next time to run given an arbitrary date/time.

_Originally posted by @llucax in https://github.com/frequenz-floss/frequenz-dispatch-python/pull/9#discussion_r1539748212_

**Comment by Marenz** [comment]
This is or will be done through https://github.com/frequenz-floss/frequenz-dispatch-python/pull/22

**Comment by llucax** [comment]
Why closing it before it is merged? I would just link the PR and let the issue closes itself when it is really done.

**Comment by Marenz** [comment]
Mainly because it's in the wrong repository where this feature is implemented
